name: Build deb with rootless

on:
  push:
  workflow_dispatch:
    #tags:
    #  - 'v*'

    #branches: [ master ]
  

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: me.tale.panic
          path: ${{ github.workspace }}/packages/*.deb
      - name: Publish artifact to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/packages/*.deb
